version: '3.0'

services:

  react:
    container_name: react-app
    build: 
      context: ./conf/react
    ports: 
    - "3000:3000"


  rasa:
    container_name: rasa
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command:
    - run

  action_server:
    container_name:  rasa-action
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  duckling:
    container_name: rasa-duckling
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

networks: {rasa-network: {}}